---
apiVersion: v1
kind: Namespace
metadata:
  name: sys-gen-contracts

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: sys-gen-contracts
type: Opaque
stringData:
  username: postgres
  password: "Elmomer@123_XD:3"

---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: sys-gen-contracts
spec:
  instances: 3
  imageName: postgres-contract-sys:18.1
  imagePullPolicy: Never
  
  postgresql:
    parameters:
      wal_level: "logical"
      max_wal_senders: "10"
      max_replication_slots: "10"
      pglogical.conflict_resolution: "last_update_wins"
      max_connections: "100"
  
  bootstrap:
    initdb:
      database: sys-gen-contracts
      owner: postgres
      secret:
        name: postgres-credentials
  
  storage:
    size: 20Gi
