apiVersion: v1
kind: Secret
metadata:
  name: contratos-secret
type: Opaque
stringData:
  username: arelyxl # <-- USUARIO ACTUALIZADO
  password: Elmomer@123_XD:3 # <-- CONTRASEÑA DÉBIL (¡Actualizar luego!)
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: contratos-db-cluster
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  storage:
    size: 20Gi # <-- TAMAÑO ACTUALIZADO
    storageClass: local-path
  bootstrap:
    initdb:
      database: sys-gen-contracts # <-- DB ACTUALIZADA
      owner: arelyxl # <-- OWNER ACTUALIZADO
      secret:
        name: contratos-secret
  postgresql:
    parameters:
      shared_preload_libraries: 'pg_stat_statements'
